[package]
name = "dllup-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5"
lazy_static = "1"
shell-words = "1.1"
inkjet = "0.11.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"

[features]
default = []
